# Generated by Django 6.0.6 on 2026-06-26 06:14

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('clubs', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='club',
            name='email',
        ),
    ]
